@extends('layouts.app')

@section('content')
  <a href="/posts" class="btn btn-default">Go back</a>
  <div class="card">
    <h1>The following image is generated by AI to suit the post '{!!$post->title!!}'. Isn't it great!</h1>
    <img src="{{$url}}">
  </div>
@endsection